### ISSUE TITLE
导入工程多个System.Runtime.CompilerServices.Unsafe.dll

### ISSUE THREAD

**Issue by yslinwe** [sunsvip/GF_X#10]
unity版本 2021.3.27f1导入后，有两个System.Runtime.CompilerServices.Unsafe报错，如果删掉Zstring 的里的打包报错。

![image](https://github.com/user-attachments/assets/08169d68-fd36-492b-998f-07a21f735201)
![image](https://github.com/user-attachments/assets/72a41b92-1f58-4073-8c59-635680dce1c7)

**Comment by sunsvip** [comment]
可直接把CompressImageLibs下的重复dll禁用, 如下图。或者升级为Unity2022及以上版本
![image](https://github.com/user-attachments/assets/475f68d2-275f-4712-8099-b1ac442f6463)

**Comment by sunsvip** [comment]
已修复
