### ISSUE TITLE
热更带mono的程序集找不到脚本资源

### ISSUE THREAD

**Issue by HeriseEx** [sunsvip/GF_X#12]
在Hotfix同级目录下导入了一个UI插件包
![image](https://github.com/user-attachments/assets/bbc1b11b-9b40-4de7-83db-9f3339aef634)
![image](https://github.com/user-attachments/assets/f1df4fe2-366d-4c46-8491-721b65a95a9a)
程序集引用和AB包打包均正常，热更流程正常，但是当预制体实例的时候会报错找不到脚本

============================================================
如果将该包的脚本全部移动到hotfix程序集中，热更之后实例化则是正常的。这是什么原因呢？

**Comment by sunsvip** [comment]
这是HybridCLR使用方式的错误，新增的插件如果放到Hotfix程序集下就把插件的asmdef删掉。正确做法是把插件放到Hotfix之外作为独立的程序集，配置到HybridCLR Settings热更dlls列表里。

**Comment by HeriseEx** [comment]
这里我没有表达清楚：截图是为了表明引用配置是正确的，测试了两种形式：
1.配置了asmdef程序集的时候是没有在hotfix文件夹中的，在hotfix中对程序集进行了引用。这个时候实例化对象的时候会找不到脚本。
2.直接把整个脚本移动到hotfix中直接进行热更，这个时候是完全正常的。

==============================================
然后使用基础的dll进行热更调用也是正常的。唯独asmdef方式添加的程序集这里遇到了问题，而在模板中摇杆部分的代码也是通过asmdef进行的同样的配置，所以不知道是什么原因导致的。

**Comment by sunsvip** [comment]
> 这里我没有表达清楚：截图是为了表明引用配置是正确的，测试了两种形式： 1.配置了asmdef程序集的时候是没有在hotfix文件夹中的，在hotfix中对程序集进行了引用。这个时候实例化对象的时候会找不到脚本。 2.直接把整个脚本移动到hotfix中直接进行热更，这个时候是完全正常的。
> 
> ============================================== 然后使用基础的dll进行热更调用也是正常的。唯独asmdef方式添加的程序集这里遇到了问题，而在模板中摇杆部分的代码也是通过asmdef进行的同样的配置并且正常运行，所以不知道是什么原因导致的。

你需要把所有需要热更的程序集配置到HybridCLR里，HybridCLR正确处理后MonoBehavior才能正常使用，这是HybridCLR的机制。建议去HybridCLR新手群提问

**Comment by sunsvip** [comment]
> 这里我没有表达清楚：截图是为了表明引用配置是正确的，测试了两种形式： 1.配置了asmdef程序集的时候是没有在hotfix文件夹中的，在hotfix中对程序集进行了引用。这个时候实例化对象的时候会找不到脚本。 2.直接把整个脚本移动到hotfix中直接进行热更，这个时候是完全正常的。
> 
> ============================================== 然后使用基础的dll进行热更调用也是正常的。唯独asmdef方式添加的程序集这里遇到了问题，而在模板中摇杆部分的代码也是通过asmdef进行的同样的配置并且正常运行，所以不知道是什么原因导致的。

你需要把所有需要热更的程序集配置到HybridCLR里，HybridCLR正确处理后MonoBehavior才能正常使用，这是HybridCLR的机制。建议去HybridCLR新手群提问
