### ISSUE TITLE
配置勾选二进制生成问题

### ISSUE THREAD

**Issue by ShawnXiaoWork** [sunsvip/GF_X#15]
问题描述：
             配置表勾选Load from bytes后
             1.GameConfig表没有通过Excel生成txt再转bytes,导致Config表不会更新，并且删除GameConfig.txt或者新建Config表导出失败
![image](https://github.com/user-attachments/assets/995d513e-6ca4-4ba0-adde-e62a79c79cf4)
            2.所有得配置表包括Table，Config，Language使用二进制导出后都会生成两份文件，一份txt，一份bytes，并且这两份文件在构建资源得时候都会打包
![image](https://github.com/user-attachments/assets/d15e61e1-8a99-4ae8-bf1c-31365d513fc9)

**Comment by sunsvip** [comment]
> 问题描述： 配置表勾选Load from bytes后 1.GameConfig表没有通过Excel生成txt再转bytes,导致Config表不会更新，并且删除GameConfig.txt或者新建Config表导出失败 ![image](https://private-user-images.githubusercontent.com/6456752/393172075-995d513e-6ca4-4ba0-adde-e62a79c79cf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzgyMDcsIm5iZiI6MTczMzQ3NzkwNywicGF0aCI6Ii82NDU2NzUyLzM5MzE3MjA3NS05OTVkNTEzZS02Y2E0LTRiYTAtYWRkZS1lNjJhNzljNzljZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMDkzODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU0YjdjZDU2MDIxZjg2YWMzYmM3Mzk2NjNlZjUwMDcxYTYwMWRiNDcxMzY0ODIxZjc3ODkyZDY2YmYxODZiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qInBAOVGJ5dLquGksSOy71MfHyeK0OviiC7yNU7bf2w) 2.所有得配置表包括Table，Config，Language使用二进制导出后都会生成两份文件，一份txt，一份bytes，并且这两份文件在构建资源得时候都会打包 ![image](https://private-user-images.githubusercontent.com/6456752/393174456-d15e61e1-8a99-4ae8-bf1c-31365d513fc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzgyMDcsIm5iZiI6MTczMzQ3NzkwNywicGF0aCI6Ii82NDU2NzUyLzM5MzE3NDQ1Ni1kMTVlNjFlMS04YTk5LTRhZTgtYmYxYy0zMTM2NWQ1MTNmYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMDkzODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2M2OGQzZjgyYWM3NzRhYTVjYjMyZmM5ZmZkODI0OTU0NmRhNGJjZDk5Y2RmMmRiM2NiMWMxMzE4YzMyYmNjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AaznqDTsMl0eVLzxDaeifWsY15Yh4UDRk1PHlxbxJHw)

1. 需手动Game Framework->GameTools->RefrshAllExcels重新导出所有。勾选Load from bytes后，Config与多语言都不需要解析数据类型，因此直接从Excel导出二进制文件(不会导出txt)。加载txt还是bytes由Load from bytes决定。
2. 数据表同时存在txt、bytes易于开发阶段debug，至于都打进包的问题，GF_X集成了Resource Rule Editor，用户根据自己需求自行过滤文件。如：
![image](https://github.com/user-attachments/assets/d55e6480-da97-47ff-9f82-722c7573cb21)
